const {chromium}=require(process.env.RSI_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.RSI_TEST_URL||'http://127.0.0.1:8765/app/';
 const go=async hash=>{await page.goto(base+'?demo#'+hash);await page.locator('#runtime').filter({hasText:'Demonstração'}).waitFor();};
 const done=async()=>{await page.locator('#busy').waitFor({state:'hidden'});};
 await go('inicio');await page.screenshot({path:'/tmp/rsi-visual/desktop-final.png'});
 await go('tarefas');await page.getByLabel('Nova tarefa').fill('<script>teste</script>');await page.getByLabel('Prazo opcional').fill('2026-10-01');await page.getByRole('button',{name:'Adicionar tarefa',exact:true}).click();await done();assert.equal(await page.locator('.task-row').count(),1);assert.equal(await page.locator('main script').count(),0);
 const icsPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar calendário (.ics)'}).click();const ics=await icsPromise;assert.ok(fs.readFileSync(await ics.path(),'utf8').includes('DTSTART;VALUE=DATE:20261001'));
 await page.locator('.task-toggle').click();await done();await page.getByRole('button',{name:'Concluídas',exact:true}).click();assert.equal(await page.locator('.task-row.done').count(),1);
 await go('memoria');await page.getByLabel('Título',{exact:true}).fill('Política de proposta');await page.getByLabel('Conteúdo',{exact:true}).fill('Proposta inclui duas revisões.');await page.getByRole('button',{name:'Salvar conhecimento',exact:true}).click();await done();await page.getByLabel('Buscar no conhecimento').fill('ausente');assert.equal(await page.locator('.memory-row').count(),0);await page.getByLabel('Buscar no conhecimento').fill('proposta');assert.equal(await page.locator('.memory-row').count(),1);
 await go('avulsa');await page.getByLabel('O que você quer resolver?').fill('Prepare uma proposta de 4 posts.');await page.getByRole('button',{name:'Preparar entrega',exact:true}).click();await done();await page.locator('.output').waitFor();assert.ok((await page.locator('.output').innerText()).includes('EXEMPLO PROGRAMADO'));
 await page.getByRole('button',{name:'Adicionar próximos passos às tarefas',exact:true}).click();await done();assert.equal(await page.getByRole('button',{name:'Próximos passos adicionados',exact:true}).isDisabled(),true);
 await page.getByLabel('O que manter ou corrigir').fill('Explicitar prazo.');await page.getByRole('button',{name:'Registrar avaliação',exact:true}).click();await done();
 await go('laboratorio');await page.getByLabel('Objetivo da mudança').fill('Explicitar o que falta antes de sugerir prazo.');await page.getByRole('button',{name:'Propor nova instrução',exact:true}).click();await done();await page.getByRole('button',{name:'Comparar em 3 casos · exemplos',exact:true}).click();await done();assert.equal(await page.locator('.experiment').count(),1);await page.getByLabel('Seu parecer após comparar os três casos').fill('Revisei os três exemplos. Demonstração apenas.');await page.getByLabel('Revisei os resultados e aprovo usar esta instrução nos três espaços.').check();await page.getByRole('button',{name:'Promover instrução na demonstração',exact:true}).click();await done();assert.equal(await page.locator('#active-version').innerText(),'Proposta de demonstração');await page.getByRole('button',{name:'Restaurar',exact:true}).click();await done();assert.equal(await page.locator('#active-version').innerText(),'Instrução inicial');
 await go('rotinas');await page.getByLabel('Nome',{exact:true}).fill('Revisão semanal');await page.getByLabel('Pedido para o assistente').fill('Organize minha semana');await page.getByRole('button',{name:'Salvar rotina',exact:true}).click();await done();assert.equal(await page.getByRole('button',{name:'Executar agora',exact:true}).count(),1);
 await page.locator('#profile').selectOption('empresa');await done();assert.equal(await page.getByRole('button',{name:'Executar agora',exact:true}).count(),0);await page.locator('#profile').selectOption('pessoal');await done();
 await go('configuracoes');const dlPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Baixar backup JSON',exact:true}).click();const dl=await dlPromise;const backup=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert.equal(backup.schema,1);assert.equal(backup.runs.length,1);assert.equal(backup.tasks.length,4);
 // Malformed backup must not replace valid state.
 const malformed=JSON.stringify({...backup,runs:[{id:'bad'}]});await page.locator('input[type=file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(malformed)});await page.locator('input[name=confirm]').check();await page.getByRole('button',{name:'Restaurar backup',exact:true}).click();await page.locator('#toast').filter({hasText:'inválido'}).waitFor();await done();
 await page.locator('input[type=file]').setInputFiles({name:'ok.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.getByRole('button',{name:'Restaurar backup',exact:true}).click();await page.locator('#toast').filter({hasText:'restaurado'}).waitFor();await done();
 await page.reload();await page.locator('#runtime').filter({hasText:'Demonstração'}).waitFor();
 // Every view must fit mobile and render without exceptions in both themes.
 for(const width of [360,1440]){await page.setViewportSize({width,height:900});for(const theme of ['dark','light']){await page.evaluate(t=>{document.body.classList.toggle('light',t==='light');localStorage.setItem('rsi-theme',t);},theme);for(const route of ['inicio','assistente','avulsa','tarefas','memoria','rotinas','laboratorio','historico','configuracoes']){await go(route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width} ${theme} ${route}`);}}}
 await page.evaluate(()=>{localStorage.removeItem('rsi-copiloto-demo-v1');localStorage.setItem('rsi-theme','dark');});await page.setViewportSize({width:360,height:850});await go('inicio');await page.screenshot({path:'/tmp/rsi-visual/mobile-final.png'});
 // Local API adapter with the real server: persistent data, no paid call here.
 await page.goto(base+'#tarefas');await page.locator('#runtime').filter({hasText:'IA conectada'}).waitFor();await page.getByLabel('Nova tarefa').fill('Teste via API local');await page.getByRole('button',{name:'Adicionar tarefa',exact:true}).click();await done();await page.reload();await page.locator('.task-row').filter({hasText:'Teste via API local'}).waitFor();await page.locator('.task-row').filter({hasText:'Teste via API local'}).getByRole('button',{name:'Excluir',exact:true}).click();await done();
 assert.deepEqual(errors,[]);console.log('PASS: full demo lifecycle, profile isolation, exports, malformed/valid backup, persistence, 36 responsive route/theme checks, live API adapter; zero page errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
