/* Offline adapter. No network request, credentials or synthetic quality claims. */
window.RSIDemo=class {
  constructor(catalog){this.catalog=catalog;this.key='rsi-copiloto-demo-v1';this.model='Exemplo programado';}
  initial(){return {schema:1,missions:[],version:'1.1.0',profile:'pessoal',tasks:[],memories:[],runs:[],candidates:[],experiments:[],routines:[],audit:[],usage:[],versions:[{id:'base',name:'Instrução inicial',prompt:this.catalog.base,created:new Date().toISOString()}],active:'base'};}
  read(){const raw=localStorage.getItem(this.key);let s=raw?JSON.parse(raw):this.initial();if(s.schema!==1||!Array.isArray(s.tasks))throw Error('Dados locais incompatíveis. Exporte ou restaure um backup válido.');s.missions=s.missions||[];s.version='1.1.0';return {...s,playbooks:this.catalog.playbooks,runtime:{mode:'demo',configured:false,model:this.model,daily_limit:0,calls_today:0}};}
  save(s){const data=structuredClone(s);delete data.runtime;delete data.playbooks;localStorage.setItem(this.key,JSON.stringify(data));}
  output(prompt,s,improved=false){const memories=s.memories.filter(m=>[s.profile,'todos'].includes(m.profile)&&m.body.toLowerCase().split(/\s+/).some(w=>w.length>3&&prompt.toLowerCase().includes(w))).slice(0,5);return {title:'Plano de trabalho para revisar',answer:'EXEMPLO PROGRAMADO · sem chamada de IA\n\nDemanda registrada:\n'+prompt+'\n\n1. Preparação\nReúna o material disponível e defina o resultado que precisa obter.\n\n2. Execução\nDivida a demanda em uma primeira entrega pequena. Reserve um período de trabalho e confirme as informações que faltam.\n\n3. Conferência\nRevise fatos, tom e próximos passos antes de compartilhar a entrega. Anote o que precisou corrigir para orientar a próxima versão.'+(improved?'\n\nCritério adicional do exemplo: validar a entrega com uma lista explícita de requisitos.':''),assumptions:['Este roteiro é um exemplo fixo; a versão local com IA produz uma entrega específica.','Prazo, responsável e critérios finais ainda precisam ser confirmados.'],actions:['Reunir informações da demanda','Preparar a primeira versão da entrega','Revisar o resultado e registrar feedback'],sources:memories.map(m=>m.id)};}
  async action(action,d){const s=this.read(), id=()=>crypto.randomUUID().replaceAll('-','').slice(0,16),now=()=>new Date().toISOString();const get=(k,x)=>{const row=s[k].find(r=>r.id===x);if(!row)throw Error('Registro não encontrado.');return row;};const audit=(event,detail)=>s.audit.unshift({id:id(),at:now(),event,detail});let result=null;
    if(action.startsWith('mission.')){result=demoMission(this,s,action,d);}
    else if(action==='profile')s.profile=d.profile;
    else if(action==='task.add'){result={id:id(),title:d.title.trim(),due:d.due||'',status:'open',profile:s.profile,created:now()};s.tasks.unshift(result);audit(action,result.title);}
    else if(action==='task.toggle'){let r=get('tasks',d.id);r.status=r.status==='open'?'done':'open';audit(action,r.title);}
    else if(['task.delete','memory.delete','routine.delete'].includes(action)){const k={'task.delete':'tasks','memory.delete':'memories','routine.delete':'routines'}[action];get(k,d.id);s[k]=s[k].filter(r=>r.id!==d.id);audit(action,'Registro removido');}
    else if(action==='memory.add'){result={id:id(),title:d.title.trim(),body:d.body.trim(),profile:d.shared?'todos':s.profile,created:now()};s.memories.unshift(result);audit(action,result.title);}
    else if(action==='run'){const output=this.output(d.prompt,s,s.active!=='base');result={id:id(),prompt:d.prompt,output,meta:{model:this.model,tokens:0,cost:0,seconds:0},profile:s.profile,version:s.active,created:now(),feedback:null,applied:false,context:s.memories.filter(m=>output.sources.includes(m.id)).map(m=>({id:m.id,title:m.title}))};s.runs.unshift(result);audit(action,'Entrega de demonstração');}
    else if(action==='run.apply'){const r=get('runs',d.id);if(r.applied)throw Error('Os próximos passos já viraram tarefas.');r.output.actions.forEach(title=>s.tasks.unshift({id:id(),title,due:'',status:'open',profile:r.profile,created:now()}));r.applied=true;audit(action,r.output.title);}
    else if(action==='feedback'){const r=get('runs',d.id);r.feedback={rating:d.rating,note:d.note,at:now()};audit(action,`${d.rating}/5 · ${r.output.title}`);}
    else if(action==='candidate'){if(d.mission){const m=get('missions',d.mission);if(m.status!=='completed'||m.profile!==s.profile)throw Error('Conclua a missão antes de iniciar o LOOP-R.');}result={id:id(),name:'Proposta de demonstração',prompt:this.catalog.base+'\nMelhoria solicitada: '+d.goal,rationale:'Exemplo programado: acrescenta o objetivo informado à instrução. A versão local usa a IA e os feedbacks para elaborar a proposta.',base:s.active,created:now(),meta:{model:this.model},profile:s.profile};result.mission=d.mission||null;s.candidates.unshift(result);audit(action,result.name);}
    else if(action==='evaluate'){const c=get('candidates',d.id);if(c.base!==s.active)throw Error('A versão ativa mudou. Proponha um novo candidato.');const cases=this.catalog.cases.map(k=>({...k,baseline:{output:this.output(k.input,{...s,memories:[]}),metrics:{score:100,checks:{entrega_substancial:true,passos_concisos:true,lacunas_explicitas:true,tamanho_controlado:true}}},candidate:{output:this.output(k.input,{...s,memories:[]},true),metrics:{score:100,checks:{entrega_substancial:true,passos_concisos:true,lacunas_explicitas:true,tamanho_controlado:true}}}}));result={id:id(),candidate:c.id,base:s.active,created:now(),cases,scores:{baseline:100,candidate:100},eligible:true,review:null,mode:'demo',profile:s.profile};s.experiments.unshift(result);audit(action,'Comparação de exemplos programados; não mede ganho real.');}
    else if(action==='promote'){const e=get('experiments',d.id);if(!d.approved||!d.review.trim())throw Error('Registre a revisão e confirme a aprovação.');if(!e.eligible||e.base!==s.active)throw Error('Comparação inválida ou desatualizada.');const c=get('candidates',e.candidate);if(s.versions.some(v=>v.id===c.id))throw Error('Versão já promovida.');s.versions.push({id:c.id,name:c.name,prompt:c.prompt,created:c.created});s.active=c.id;e.review={note:d.review,at:now()};audit(action,c.name);}
    else if(action==='rollback'){s.active=get('versions',d.id).id;audit(action,'Versão restaurada');}
    else if(action==='routine.add'){result={id:id(),name:d.name,prompt:d.prompt,profile:s.profile,enabled:false,next:now(),last:null,error:null};s.routines.unshift(result);audit(action,d.name);}
    else if(action==='routine.toggle')throw Error('Recorrência automática disponível na versão local com servidor aberto. Na demonstração, use Executar agora.');
    else if(action==='restore'){if(!d.backup||d.backup.schema!==1||!['pessoal','autonomo','empresa'].includes(d.backup.profile))throw Error('Backup incompatível.');const b=validateRSIBackup(d.backup);for(const key of ['tasks','memories','runs','versions','candidates','experiments','routines','audit','usage'])if(!Array.isArray(b[key])||b[key].some(x=>!x||typeof x.id!=='string'))throw Error('Backup incompleto.');if(!b.versions.some(v=>v.id===b.active))throw Error('Versão ativa ausente.');b.routines.forEach(r=>r.enabled=false);b.experiments.forEach(e=>e.eligible=false);this.save(b);return {result:null,state:this.read()};}
    else throw Error('Ação desconhecida.');
    s.audit=s.audit.slice(0,500);this.save(s);return {result,state:this.read()};
  }
};
