/* Mission navigation and offline state machine. Production execution lives on the server. */
let selectedMissionId=localStorage.getItem('rsi-selected-mission');
const missionLabels={plan:'Aguardando aprovação do plano',ready:'Pronta para executar',review:'Entrega aguardando sua avaliação',manual:'Depende de ação sua fora do sistema',paused:'Pausada',completed:'Missão concluída',cancelled:'Cancelada'};
function missionComposer(){return `<form id="mission-form" class="form-grid"><label for="mission-goal">Qual missão você quer delegar?</label><textarea id="mission-goal" name="goal" required maxlength="6000" placeholder="Ex.: produza uma proposta comercial de 8 posts, com escopo, exclusões e uma mensagem de apresentação. Não envie nada ao cliente."></textarea><small>${state.runtime.mode==='demo'?'Simulação: o fluxo funciona com exemplos fixos. Para executar sua missão com IA, abra a versão local.':'A IA vai propor um plano. A execução começa depois da sua aprovação.'}</small><button class="primary" type="submit">Preparar plano da missão</button></form>`;}
function currentMission(){return mine('missions').find(m=>m.id===selectedMissionId)||mine('missions')[0];}
function missionView(){const m=currentMission();const list=mine('missions');return head('Você aprova. O copiloto continua.','Delegue a missão, aprove o plano e avalie cada entrega. A correção acontece na mesma etapa.')+`<div class="notice"><strong>Execução:</strong> plano → sua aprovação → entrega → sua avaliação → próxima etapa.<br><strong>Evolução RSI:</strong> falhas e avaliações → nova instrução → comparação → sua aprovação → próximas missões.</div>${m?`<details><summary>Iniciar outra missão</summary>${missionComposer()}</details>`:`<section class="panel">${missionComposer()}</section>`}${list.length?`<label class="mission-picker">Missão em acompanhamento<select id="mission-picker">${list.map(x=>`<option value="${esc(x.id)}" ${x.id===m.id?'selected':''}>${esc(x.title)} · ${missionLabels[x.status]}</option>`).join('')}</select></label>`:''}${m?missionDetail(m):empty('A memória é contexto, não o próximo botão.','Depois de pedir a missão, aprove o plano aqui. O sistema produz a primeira entrega e volta para sua avaliação.')}<p class="overview-note"><a class="link" href="#avulsa">Preciso apenas de uma entrega avulsa →</a></p>`;}
function missionDetail(m){const step=m.steps[m.current];const last=step?.attempts.at(-1);const complete=m.status==='completed';const finished=['completed','cancelled'].includes(m.status);return `<section class="mission-detail panel" data-mission="${esc(m.id)}"><div class="tags">${tag(missionLabels[m.status],'amber')}${tag(state.runtime.mode==='demo'?'Simulação sem IA':'Execução com IA')}${tag(`${m.steps.filter(x=>x.status==='approved').length}/${m.steps.length} etapas aprovadas`)}</div><h2 class="mission-heading" style="margin-top:20px">${esc(m.title)}</h2><p class="muted">${esc(m.goal)}</p><ol class="mission-steps">${m.steps.map((x,i)=>`<li class="${i===m.current?'current':''}"><strong>${i+1}. ${esc(x.title)}</strong><span>${x.status==='approved'?'Aprovada':i===m.current?missionLabels[m.status]:'Ainda não executada'} · ${x.kind==='manual'?'Ação manual':'Entrega de texto pela IA'}</span>${m.status==='plan'?`<p>${esc(x.instruction)}</p>`:''}${x.attempts.length&&i!==m.current?`<details><summary>Ver entrega e avaliação</summary><div class="prose">${esc(x.attempts.at(-1).output.answer)}</div><p class="notice">${esc(x.review?.note||'Sem aprovação')}</p></details>`:''}</li>`).join('')}</ol>${m.error?`<p class="notice error-panel"><strong>A etapa não foi concluída:</strong> ${esc(m.error)}. As aprovações anteriores estão salvas. Tente executar novamente.</p>`:''}
${m.status==='plan'?`<p>Confira a ordem e o tipo das etapas. Ações manuais exigirão que você faça o trabalho fora do sistema e informe o resultado.</p><div class="actions">${button('mission.start','Aprovar plano e executar primeira etapa',m.id,'primary')}</div><details><summary>Pedir ajuste no plano</summary><form class="mission-replan form-grid"><label>O que precisa mudar?<textarea name="note" required maxlength="2000"></textarea></label><button type="submit">Refazer plano</button></form></details>`:''}
${m.status==='ready'?`<div class="actions">${button('mission.retry','Executar etapa pendente',m.id,'primary')}</div>`:''}
${m.status==='review'&&last?`<div class="mission-delivery"><h2>Etapa ${m.current+1}: entrega para avaliar</h2><div class="prose">${esc(last.output.answer)}</div><h3>Lacunas</h3><ul>${last.output.assumptions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><small>Versão ${step.attempts.length} desta entrega. Instrução da missão: ${esc(state.versions.find(x=>x.id===m.version)?.name||m.version)}.</small><form class="mission-review form-grid"><label>Como ficou?<select name="rating">${[5,4,3,2,1].map(n=>`<option value="${n}">${n}/5</option>`).join('')}</select></label><label>Avaliação ou correção para o copiloto<textarea name="note" maxlength="2000" placeholder="Ex.: inclua as exclusões do escopo. Sua avaliação acompanha o trabalho e alimenta o ciclo RSI."></textarea></label><div class="actions"><button type="submit" name="decision" value="approve" class="primary">${m.current===m.steps.length-1?'Aprovar entrega e concluir missão':'Aprovar e executar próxima etapa'}</button><button type="submit" name="decision" value="revise">Corrigir esta etapa</button></div></form><p class="overview-note">Não precisa salvar na memória: o resultado e sua avaliação já ficam na missão. Aprovar dispara a próxima etapa automaticamente.</p><details><summary>Ver versões anteriores desta etapa (${step.attempts.length})</summary>${step.attempts.map((a,i)=>`<h3>Versão ${i+1}</h3><div class="prose">${esc(a.output.answer)}</div>`).join('')}</details></div>`:''}
${m.status==='manual'?`<h2>Esta etapa precisa de você</h2><p>${esc(step.instruction)}</p><p class="notice">O sistema não executou esta ação externa. Não há integração para fazê-la automaticamente. Realize a ação fora daqui ou pause a missão.</p><form class="mission-manual form-grid"><label>O que foi feito ou qual informação foi obtida?<textarea name="note" required maxlength="2000" placeholder="Informe o resultado real. Ele será usado na próxima etapa."></textarea></label><button class="primary" type="submit">Registrar resultado manual e continuar</button></form>`:''}
${m.status==='paused'?button('mission.resume','Retomar missão',m.id,'primary'):''}
${complete?`<h2>Entregas aprovadas. Agora, o LOOP-R.</h2>${missionMetrics(m)}<p>As avaliações e correções desta missão podem orientar uma nova instrução para missões futuras. Primeiro compare a candidata no laboratório; a mudança só entra em uso após sua aprovação.</p><div class="actions">${button('mission.export','Baixar entregas aprovadas',m.id,'primary')}${button('mission.evolve','Iniciar LOOP-R desta missão',m.id)}</div><p class="overview-note">Propor não altera a instrução ativa. Os testes atuais verificam estrutura em três exemplos gerais; revise também se a mudança atende seu caso.</p>`:''}
${!finished?`<div class="actions mission-secondary">${m.status!=='paused'?button('mission.pause','Pausar missão',m.id,'quiet'):''}${button('mission.cancel','Cancelar missão',m.id,'quiet danger')}</div>`:''}</section>`;}
async function missionAction(action,data={}){const m=currentMission();const result=await act(action,{id:m.id,revision:m.revision,...data},action==='mission.approve'?'Registrando avaliação e executando a próxima etapa…':action==='mission.revise'?'Corrigindo a entrega com sua orientação…':'Processando missão…');render();if(result.error)toast(result.error,true);else toast(missionLabels[result.status]);}
function missionRSIGoal(m){return ('Melhore a instrução para próximas missões semelhantes a: '+m.goal+'\nAvaliações desta missão: '+m.steps.map(x=>x.title+': '+(x.review?.note||'')+(x.feedback?' Correção solicitada: '+x.feedback:'')).join('\n')).slice(0,2000);}
function demoMission(adapter,s,action,d){const id=()=>crypto.randomUUID().replaceAll('-','').slice(0,16),now=()=>new Date().toISOString();const log=()=>s.audit.unshift({id:id(),at:now(),event:action,detail:'Missão: '+m.title});let m=s.missions.find(x=>x.id===d.id);
 const makeSteps=()=>{const en=window.RSI_LANGUAGE==='en',es=window.RSI_LANGUAGE==='es',titles=en?['Prepare first draft','Finalize deliverable']:es?['Preparar el primer borrador','Consolidar la entrega final']:['Preparar primeira versão','Consolidar entrega final'];return titles.map((title,i)=>({id:id(),title,instruction:i?(en?'Finalize the previous deliverable using your feedback.':es?'Consolidar la entrega anterior incorporando tu evaluación.':'Consolidar a entrega anterior incorporando sua avaliação.'):(en?'Prepare a first draft for your review.':es?'Preparar un primer borrador para que lo evalúes.':'Produzir uma primeira versão para sua avaliação.'),kind:'draft',status:'pending',attempts:[],review:null,feedback:''}));};
 if(action==='mission.create'){m={id:id(),goal:d.goal,title:d.goal.slice(0,100),profile:s.profile,created:now(),status:'plan',current:0,revision:0,steps:makeSteps(),error:null,resume:null,version:s.active,instruction:s.versions.find(v=>v.id===s.active).prompt,plan_meta:{model:window.RSI_LANGUAGE==='en'?'Scripted example':window.RSI_LANGUAGE==='es'?'Ejemplo programado':'Exemplo programado'}};s.missions.unshift(m);log();return m;}
 if(!m||d.revision!==m.revision)throw Error('Esta missão mudou. Recarregue a página.');if(m.profile!==s.profile)throw Error('Abra o espaço da missão.');
 const requireState=status=>{if(m.status!==status)throw Error('Ação indisponível nesta etapa.');};
 if(action==='mission.pause'){if(!['plan','ready','review','manual'].includes(m.status))throw Error('Missão encerrada.');m.resume=m.status;m.status='paused';}
 else if(action==='mission.resume'){requireState('paused');m.status=m.resume;m.resume=null;}
 else if(action==='mission.cancel'){if(['completed','cancelled'].includes(m.status))throw Error('Missão encerrada.');m.status='cancelled';}
 else if(action==='mission.replan'){requireState('plan');if(!d.note.trim())throw Error('Descreva o ajuste.');m.steps=makeSteps();m.steps[0].instruction+=' Ajuste solicitado: '+d.note;}
 else{const expected={'mission.start':'plan','mission.retry':'ready','mission.revise':'review','mission.approve':'review','mission.manual':'manual'}[action];if(!expected)throw Error('Ação desconhecida.');requireState(expected);let step=m.steps[m.current];
 if(action==='mission.revise'){if(!d.note.trim())throw Error('Descreva o que deve ser corrigido.');if(step.attempts.length>=10)throw Error('Limite de 10 versões nesta etapa.');step.feedback=d.note;const r=s.runs.find(x=>x.id===step.attempts.at(-1).run);r.feedback={rating:2,note:d.note,at:now()};}
 if(['mission.approve','mission.manual'].includes(action)){if(action==='mission.manual'&&!d.note.trim())throw Error('Informe o resultado manual.');step.review={rating:d.rating||5,note:d.note||'Aprovado sem ressalvas.',at:now()};step.status='approved';if(step.attempts.length)s.runs.find(x=>x.id===step.attempts.at(-1).run).feedback={...step.review};m.current++;}
 if(m.current===m.steps.length)m.status='completed';else{step=m.steps[m.current];if(step.kind==='manual'){step.status='manual';m.status='manual';}else{const lang=window.RSI_LANGUAGE,en=lang==='en',es=lang==='es';const output={title:step.title,answer:(en?'SIMULATION · SCRIPTED EXAMPLE, NO AI':es?'SIMULACIÓN · EJEMPLO PROGRAMADO, SIN IA':'SIMULAÇÃO · EXEMPLO PROGRAMADO, SEM IA')+'\n\n'+(en?'Mission: ':es?'Misión: ':'Missão: ')+m.goal+'\n\n'+(m.current===0?(en?'Sample first deliverable:\nGoal recorded and materials organized for review. In the local version, AI writes content tailored to your mission.':es?'Primera entrega de ejemplo:\nObjetivo registrado y material organizado para revisión. En la versión local, la IA redacta contenido específico para tu misión.':'Primeira entrega de exemplo:\nObjetivo registrado, material organizado para revisão. Na versão local a IA redige o conteúdo específico da sua missão.'):(en?'Sample final deliverable:\nThis step received the previous result and your review: ':es?'Entrega final de ejemplo:\nEsta etapa recibió el resultado anterior y tu evaluación: ':'Entrega final de exemplo:\nEsta etapa recebeu o resultado anterior e sua avaliação: ')+m.steps[0].review.note+'\n'+(en?'In the local version, AI consolidates the approved content.':es?'En la versión local, la IA consolida el contenido aprobado.':'Na versão local a IA consolida o conteúdo aprovado.'))+(step.feedback?'\n\n'+(en?'Revision recorded for this version: ':es?'Corrección registrada para esta versión: ':'Correção registrada para esta versão: ')+step.feedback:''),assumptions:[en?'This simulation shows approval and continuity; it does not run your mission with AI.':es?'Esta simulación muestra la aprobación y la continuidad; no ejecuta tu misión con IA.':'Esta simulação demonstra aprovação e continuidade; não executa sua missão com IA.'],actions:[en?'Review this step’s deliverable':es?'Revisar la entrega de esta etapa':'Revisar a entrega desta etapa'],sources:[]};const run={id:id(),prompt:m.goal+' — '+step.title,output,meta:{model:adapter.model,tokens:0,cost:0,seconds:0},profile:m.profile,version:m.version,created:now(),feedback:null,applied:false,context:[]};s.runs.unshift(run);step.attempts.push({run:run.id,output,created:now(),context:[]});step.status='review';m.status='review';}}}
 m.revision++;m.error=null;log();return m;
}

function missionMetrics(m){const reviews=m.steps.filter(x=>x.review);const average=reviews.length?(reviews.reduce((n,x)=>n+x.review.rating,0)/reviews.length).toFixed(1):'—';const corrections=m.steps.reduce((n,x)=>n+Math.max(0,x.attempts.length-1),0);const candidates=state.candidates.filter(c=>c.mission===m.id);const promoted=candidates.some(c=>state.versions.some(v=>v.id===c.id));return `<div class="notice"><strong>Medir:</strong> nota média ${average}/5 · ${corrections} correções · ${reviews.length} etapas aprovadas.<br><strong>Criticar:</strong> seus comentários e as versões anteriores acompanham a proposta.<br><strong>Propor → Testar → Validar → Promover:</strong> ${promoted?'há instrução promovida a partir desta missão.':candidates.length?'proposta criada; acompanhe comparação e aprovação no laboratório.':'aguardando iniciar a melhoria.'}<br><strong>Repetir:</strong> novas missões usam a instrução ativa; esta missão mantém sua versão original.</div>${candidates.length?'<a class="link" href="#laboratorio">Acompanhar propostas e comparações →</a>':''}`;}
